name: Build Wheels (Linux)

on:
  workflow_dispatch:
    inputs: {}

jobs:
  linux:
    strategy:
      matrix:
        arch:
          - x86_64
          - i686
          - aarch64
          - ppc64le
          - armv7l
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: cache--${{ hashFiles('./requirements-dev.txt') }}
          path: ~/.cache/pip
  
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
  
      - run: python -m pip install -U pip wheel setuptools
      - run: python -m pip install -Ur requirements-dev.txt
      - run: python -m pip install -U 'cibuildwheel==2.*'

      - run: make prepare

      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD_FRONTEND: build
          CIBW_SKIP: 'cp27-* pp*'
          CIBW_DEPENDENCY_VERSIONS: pinned
          CIBW_PLATFORM: linux
          CIBW_TEST_COMMAND: python {project}/scripts/run-tests.py

      - uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: ./wheelhouse
