name: So, does it work?

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [
          '3.5', '3.6', '3.7', '3.8', '3.9',
          'pypy-3.5', 'pypy-3.6', 'pypy-3.7',
        ]
        
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: python -m pip install -Ur requirements.txt

      - name: Compile project
        run: make

      - name: Run JSON5 tests suite
        run: python run-tests.py

      - name: Run "JSON is a Minefield" suite
        run: python run-minefield-test.py
