name: So, does it work?

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python: [
          '3.5', '3.6', '3.7', '3.8', '3.9',
          'pypy3',
        ]
        exclude:
          - os: macos-latest
            python: pypy3
        
    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v2.1.4  # https://github.com/actions/setup-python/issues/171
        with:
          python-version: ${{ matrix.python }}

      - name: Display Python version
        run: python -c 'import sys; print(sys.version)'

      - name: Update pip
        run: python -m pip install -U pip wheel setuptools

      - name: Install requirements
        run: python -m pip install -Ur requirements.txt

      - name: Compile project
        run: make

      - name: Run JSON5 tests suite
        run: python run-tests.py

      - name: Run "JSON is a Minefield" suite
        run: python run-minefield-test.py
